let state={config:null,table:null}; const $=id=>document.getElementById(id); const send=x=>adsk.fusionSendData('fusionBomMessage',JSON.stringify(x));
window.fusionBomMessage=raw=>{const m=JSON.parse(raw); if(m.type==='error') return status(m.message,true); if(m.type==='status') return status(m.message); if(m.type==='state'){state.config=m.config;state.table=m.table;render();}};
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':''}
function render(){const v=$('view');v.innerHTML=state.config.views.map(x=>`<option value="${x.view_id}">${x.name}</option>`).join('');v.value=state.table.view_id; $('thead').innerHTML='<tr>'+state.table.columns.map(c=>`<th>${escape(c.header)}</th>`).join('')+'</tr>';$('tbody').innerHTML=state.table.rows.map(r=>'<tr>'+state.table.columns.map(c=>cell(r,c)).join('')+'</tr>').join('');renderEditor();}
function cell(row,c){let value=row.values[c.source_id]??'';if(c.source_type==='attribute')return `<td>${row.linked?`<span title="Linked - open source design to edit">${escape(value)} 🔒</span>`:`<input data-row="${row.row_id}" data-field="${c.source_id}" value="${escape(value)}">`}</td>`;return `<td>${escape(String(value))}</td>`}
function escape(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function renderEditor(){if(!state.config)return;let view=currentView();$('editView').innerHTML=state.config.views.map(x=>`<option value="${x.view_id}">${x.name}</option>`).join('');$('editView').value=view.view_id;$('viewName').value=view.name;$('field').innerHTML=state.config.fields.map(f=>`<option value="${f.field_id}">${escape(f.default_label)}</option>`).join('');$('columns').innerHTML=view.columns.map((c,i)=>`<div class="column"><input class="header" data-i="${i}" value="${escape(c.header)}"><label><input class="visible" data-i="${i}" type="checkbox" ${c.visible?'checked':''}> Visible</label><button data-move="${i},-1">←</button><button data-move="${i},1">→</button></div>`).join('');}
function currentView(){return state.config.views.find(v=>v.view_id===$('editView').value)||state.config.views[0]}
function saveConfig(){let view=currentView();view.name=$('viewName').value.trim()||view.name;document.querySelectorAll('.header').forEach(e=>view.columns[e.dataset.i].header=e.value);document.querySelectorAll('.visible').forEach(e=>view.columns[e.dataset.i].visible=e.checked);send({action:'save_config',config:state.config});}
$('refresh').onclick=()=>send({action:'refresh'});$('view').onchange=e=>{let v=state.config.views.find(x=>x.view_id===e.target.value);state.table.columns=v.columns.filter(c=>c.visible);state.table.view_id=v.view_id;render()};$('edit').onclick=()=>$('editor').showModal();$('close').onclick=()=>$('editor').close();$('editView').onchange=renderEditor;$('saveConfig').onclick=saveConfig;$('duplicate').onclick=()=>send({action:'duplicate_view',view_id:currentView().view_id,name:currentView().name+' Copy'});$('delete').onclick=()=>send({action:'delete_view',view_id:currentView().view_id});$('addColumn').onclick=()=>send({action:'add_column',view_id:currentView().view_id,field_id:$('field').value});$('addField').onclick=()=>{let label=prompt('Custom field name');if(!label)return;let id=label.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');send({action:'new_field',field_id:id,label,view_id:currentView().view_id})};$('columns').onclick=e=>{if(!e.target.dataset.move)return;let [i,d]=e.target.dataset.move.split(',').map(Number),cols=currentView().columns,j=i+d;if(j<0||j>=cols.length)return;[cols[i],cols[j]]=[cols[j],cols[i]];renderEditor()};$('tbody').onchange=e=>{if(e.target.dataset.row)send({action:'save_cell',row_id:e.target.dataset.row,field_id:e.target.dataset.field,value:e.target.value})};
