ADDIN_NAME = 'Fusion Configurable BOM'
COMMAND_ID = 'fusion_configurable_bom_open'
COMMAND_NAME = 'Open Configurable BOM'
COMMAND_DESCRIPTION = 'Open the configurable BOM palette.'
PALETTE_ID = 'fusion_configurable_bom_palette'
FIELD_ATTRIBUTE_GROUP = 'com.company.fusion_configurable_bom.fields'
CONFIG_ATTRIBUTE_GROUP = 'com.company.fusion_configurable_bom'
CONFIG_ATTRIBUTE_NAME = 'configuration'
